name: Deploy Api

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install Dependancies
        run: npm ci

      - name: Building
        run: npm run build --if-present
      
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIV_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PUB_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub
          ssh-keyscan -H ${{ secrets.OVH_IP }} >> ~/.ssh/known_hosts

      - name: Copy builds to server
        run: |
          rsync -vrm  * ${{ secrets.OVH_SSH }}:~/foogle-api

      - name: Deploy
        run: |
          ssh ${{ secrets.OVH_SSH }} "~/deploy.sh"